---
title: "사용자 접근 통제"
output:
  flexdashboard::flex_dashboard:
    css: styles-auth.css
runtime: shiny
---


```{r global, include=FALSE}

# load data in 'global' chunk so it can be shared by all users of the dashboard
library(flexdashboard)
library(shiny)
library(datasets)
library(shinymanager)
data(faithful)

# define some credentials (you can also use sqlite database)
credentials <- data.frame(
  user = c("shiny", "rstat"),
  password = c("rstat", "tidyverse"),
  stringsAsFactors = FALSE
)
```

```{r authorization}
auth_ui(id = "auth")

auth <- callModule(
  module = auth_server,
  id = "auth",
  check_credentials = check_credentials(credentials) # data.frame
  # check_credentials = check_credentials("path/to/credentials.sqlite", 
  # passphrase = "supersecret") # sqlite
)
```


Column {.sidebar}
-----------------------------------------------------------------------
  

```{r controls}
selectInput("n_breaks", label = "Number of bins:",
            choices = c(10, 20, 35, 50), selected = 20)

sliderInput("bw_adjust", label = "Bandwidth adjustment:",
            min = 0.2, max = 2, value = 1, step = 0.2)
```

Column
-----------------------------------------------------------------------

Waiting time between eruptions and the duration of the eruption for the
Old Faithful geyser in Yellowstone National Park, Wyoming, USA.
  
### Geyser Eruption Duration
  

```{r output}

renderPlot({
  hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks),
       xlab = "Duration (minutes)", main = "Geyser Eruption Duration")
  
  dens <- density(faithful$eruptions, adjust = input$bw_adjust)
  lines(dens, col = "blue")
})

```
